final_project/clock/urls.py
from django.urls import path

from . import views

app_name = 'clock'
urlpatterns = [
    path('', views.index, name='index'),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path('tasks/', views.task_list, name='task_list'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/create/', views.task_create, name='task_create'),
    path('tasks/<int:task_id>/update/', views.task_update, name='task_update'),
    path('tasks/<int:task_id>/delete/', views.task_delete, name='task_delete'),
    path('tasks/<int:task_id>/complete/', views.task_complete, name='complete_task'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/<int:category_id>/', views.category_detail, name='category_detail'),
    path('categories/create/', views.category_create, name='category_create'),
    path('categories/<int:category_id>/update/', views.category_update, name='category_update'),
    path('categories/<int:category_id>/delete/', views.category_delete, name='category_delete'),
]


final_project/final_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clock.urls')),
]

final_project/clock/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django import forms


class User(AbstractUser):
    pass

class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True,)

    def __str__(self):
        return f"{self.name}"

class Task(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    due_date = models.DateField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.user} must do {self.title} until {self.due_date}."

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description', 'user']
        widgets = {
            'user': forms.HiddenInput,
        }

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'category', 'completed', 'user']
        widgets = {
            'user': forms.HiddenInput,
        }


final_project/clock/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.db import IntegrityError
from django.http import JsonResponse
import json

from .models import Category, Task, User, CategoryForm, TaskForm
# Create your views here.

def index(request):
    return render(request, 'clock/base.html')

@login_required
def task_list(request):
    tasks = Task.objects.filter(user=request.user)
    return render(request, 'clock/task_list.html', {'tasks': tasks})

@login_required
def task_detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    return render(request, 'clock/task_detail.html', {'task': task})

@login_required
def task_create(request):
    tasks = Task.objects.filter(user=request.user)
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return render(request, 'clock/task_list.html', {'tasks': tasks})
    else:
        form = TaskForm()
    return render(request, 'clock/task_create.html', {'form': form})

@login_required
def task_update(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    tasks = Task.objects.filter(user=request.user)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save()
            return render(request, 'clock/task_list.html', {'tasks': tasks})
    else:
        form = TaskForm(instance=task)
    return render(request, 'clock/task_update.html', {'form': form})

@login_required
def task_complete(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    if request.method == 'POST':
        data = json.loads(request.body)
        task.completed = data['completed']
        task.save()
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})

@login_required
def task_delete(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    tasks = Task.objects.filter(user=request.user)
    if request.method == 'POST':
        task.delete()
        return render(request, 'clock/task_list.html', {'tasks': tasks})
    context = {
        'task': task
    }
    return render(request, 'clock/task_delete.html', context)

@login_required
def category_list(request):
    categories = Category.objects.filter(user=request.user)
    return render(request, 'clock/category_list.html', {'categories': categories})

@login_required
def category_detail(request, category_id):
    category = get_object_or_404(Category, pk=category_id, user=request.user)
    return render(request, 'clock/category_detail.html', {'category': category})

@login_required
def category_create(request):
    categories = Category.objects.filter(user=request.user)
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.user = request.user
            category.save()
            return render(request, 'clock/category_list.html', {'categories': categories})
    else:
        form = CategoryForm()
    return render(request, 'clock/category_create.html', {'form': form})

@login_required
def category_update(request, category_id):
    category = get_object_or_404(Category, pk=category_id, user=request.user)
    categories = Category.objects.filter(user=request.user)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            category = form.save()
            return render(request, 'clock/category_list.html', {'categories': categories})
    else:
        form = CategoryForm(instance=category)
    return render(request, 'clock/category_update.html', {'form': form})

@login_required
def category_delete(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    categories = Category.objects.filter(user=request.user)
    if request.method == 'POST':
        category.delete()
        return render(request, 'clock/category_list.html', {'categories': categories})
    context = {
        'category': category
    }
    return render(request, 'clock/category_delete.html', context)

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return render(request, "clock/base.html")
        else:
            return render(request, "clock/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "clock/login.html")


def logout_view(request):
    logout(request)
    return render(request, "clock/base.html")


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "clock/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "clock/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return render(request, "clock/base.html")
    else:
        return render(request, "clock/register.html")

final_project/clock/templates/clock/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Task Management</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg  navbar-light bg-warning rounded m-3">
      <a class="navbar-brand" href="{% url 'clock:index' %}">Task Management</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'clock:task_list' %}">Tasks</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'clock:category_list' %}">Categories</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'clock:logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'clock:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'clock:register' %}">Register</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container mt-5">
      
      {% block body %}
        <div class="font-italic text-center">
          {% if user.is_authenticated %}
            <h4>Hi there! Good to have you here again. Keep working on your tasks or create more of them!</h4>
            <br>
            <h4>Control your time better here.</h4>
            <br>
            <h5>Simple and pratical.</h5>
          {% else %}
            <h4>Hi there! Nice to have you here! Login/Register and stop wasting your time procrastinating. Create tasks, complete them, and feel the relief of not having to do them anymore.</h4>
            <br>
            <h4>Control your time better here.</h4>
            <br>
            <h5>Simple and pratical.</h5>
          {% endif %}
        </div>
      {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>

final_project/clock/templates/clock/category_create.html
{% extends 'clock/base.html' %}

{% block body %}
<h1 class="border-bottom font-italic pb-2">Create category</h1>
<div class="text-center m-3 p-2">
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %} 

final_project/clock/templates/clock/category_delete.html
{% extends 'clock/base.html' %}

{% block body %}
    <div class="text-center">
        <h1>Delete Category</h1>
        <p>Are you sure you want to delete the category "<strong>{{ category.name }}</strong>"?</p>
        <p class="font-italic"><strong>Once you delete a category there is no way you can access it again!</strong></p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
{% endblock %}

final_project/clock/templates/clock/category_detail.html
{% extends 'clock/base.html' %}

{% block body %}
    {% if category.user == user %}
    <div class="border rounded m-3 p-3">
      <h2 class="font-italic">{{ category.name }}</h2>
      <br>
      <p class="border-bottom">{{ category.description }}</p>
    </div>

    <div class="border rounded m-3 p-3 text-center font-italic">
      <h2><a href="{% url 'clock:category_update' category.id %}">Edit</a> or <a href="{% url 'clock:category_delete' category.id %}">Delete</a> category.</h2>
    </div>
  {% else %}
      <p>You are not authorized to view or modify this task.</p>
  {% endif %}
{% endblock %} 

final_project/clock/templates/clock/category_list.html
{% extends 'clock/base.html' %}

{% block body %}
    <h4 class="text-center font-italic">
        Create new category <a href="{% url 'clock:category_create' %}">here</a>!
    </h4>
    <br>
    <h6 class="font-italic">Note: categories are shared between all users. Feel free to add to the database and/or use it. Here is a list of your categories, you can edit and delete them. Other categories not made by you, you can only use it when creating a task.</h6>
        <h1>Category List</h1>
            {% for category in categories %}
            <div class="border rounded m-2 p-2">
                <h5><a href="{% url 'clock:category_detail' category.id %}">{{ category.name }}</a></h5>
                <br> 
                <p class="border-bottom">Description: {{ category.description }}</p>                 
            </div>
            {% endfor %}
    </ul>
{% endblock %} 

final_project/clock/templates/clock/category_update.html
{% extends 'clock/base.html' %}

{% block body %}
<h1 class="border-bottom font-italic pb-2">Edit category</h1>
<div class="text-center m-3 p-2">
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

final_project/clock/templates/clock/login.html
{% extends "clock/base.html" %}

{% block body %}

    <h2 class="text-center font-italic">Login</h2>

    {% if message %}
        <div class="text-center font-italic text-danger">{{ message }}</div>
    {% endif %}

    <form action="{% url 'clock:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-success text-center" type="submit" value="Login">
    </form>
    <br>
    <p class="text-center font-italic">Don't have an account? <a href="{% url 'clock:register' %}">Register here.</a></p>

{% endblock %}

final_project/clock/templates/clock/register.html
{% extends "clock/base.html" %}

{% block body %}

    <h2 class="text-center font-italic">Register</h2>

    {% if message %}
        <div class="text-center font-italic text-danger">{{ message }}</div>
    {% endif %}

    <form action="{% url 'clock:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-success" type="submit" value="Register">
    </form>
    <br>
    <p class="text-center font-italic">Already have an account? <a href="{% url 'clock:login' %}">Log In here.</a></p>

{% endblock %}

final_project/clock/templates/clock/task_create.html
{% extends 'clock/base.html' %}

{% block body %}
<h1 class="border-bottom font-italic pb-2">Create Task</h1>
<div class="text-center m-3 p-2">
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
</div>
{% endblock %}

final_project/clock/templates/clock/task_delete.html
{% extends 'clock/base.html' %}

{% block body %}
    <div class="text-center">
        <h1 class="border-bottom">Delete Task</h1>
        <br>
        <p>Are you sure you want to delete the task "<strong>{{ task.title }}</strong>"?</p>
        <p class="font-italic"><strong>Once you delete a task there is no way you can access it again!</strong></p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>  
{% endblock %} 

final_project/clock/templates/clock/task_detail.html
{% extends 'clock/base.html' %}

{% block body %}
    {% if task.user == user %}
      <div class="border rounded m-3 p-3">
        <h2 class="font-italic">{{ task.title }}</h2>
        <br>
        <p class="border-bottom">{{ task.description }}</p>
        <p class="border-bottom">Due Date: {{ task.due_date }}</p>
        <p class="border-bottom">Category: {{ task.category.name }}</p>
        {% if task.completed %}
            <p class="border-bottom text-success">Completed!</p>
        {% else %}
            <p class="border-bottom text-danger">Incompleted!</p>
        {% endif %}
      </div>
        {% if task.completed %}
          <button id="complete-button" class="btn btn-danger m-3 p-3" data-completed="true">Mark as Incomplete</button>
        {% else %}
          <button id="complete-button" class="btn btn-success m-3 p-3" data-completed="false">Mark as Complete</button>
        {% endif %}
      <div class="border rounded m-3 p-3 text-center font-italic">
        <h2><a href="{% url 'clock:task_update' task.id %}">Edit</a> or <a href="{% url 'clock:task_delete' task.id %}">Delete</a> task.</h2>
      </div>
    {% else %}
        <p>You are not authorized to view or modify this task.</p>
    {% endif %}

    <script>

        const url = '{% url 'clock:complete_task' task.pk %}';

        document.addEventListener('DOMContentLoaded', function() {
          const button = document.getElementById('complete-button');
          button.addEventListener('click', function() {
            const completed = this.getAttribute('data-completed') === 'true';
            const url = '/tasks/{{ task.pk }}/complete/';
            fetch(url, {
              method: 'POST',
              headers: {
                'X-CSRFToken': '{{ csrf_token }}',
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                completed: !completed
              })
            }).then(response => response.json())
              .then(data => {
                if (data.success) {
                  button.setAttribute('data-completed', !completed);
                  if (completed) {
                    button.innerHTML = 'Mark as Complete';
                    button.classList.remove('btn-success');
                    button.classList.add('btn-secondary');
                    location. reload()
                  } else {
                    button.innerHTML = 'Mark as Incomplete';
                    button.classList.remove('btn-secondary');
                    button.classList.add('btn-success');
                    location. reload()
                  }
                }
              });
          }); 
        });
      </script>
{% endblock %}



final_project/clock/templates/clock/task_list.html
{% extends 'clock/base.html' %}

{% block body %}
    <h4 class="text-center font-italic">
        Create new task <a href="{% url 'clock:task_create' %}">here</a>!
    </h4>
    <h1>Tasks List</h1>
        {% for task in tasks %}
        <div class="border rounded m-2 p-2">
            <h5><a href="{% url 'clock:task_detail' task.id %}">{{ task.title }}</a></h5>
            <br>
            <p class="border-bottom">Category: {{ task.category }}</p>
            <p class="border-bottom">Description: {{ task.description }}</p> 
            <p class="border-bottom">Due date: {{ task.due_date }}</p>
            {% if task.completed %}
                <p class="border-bottom text-success">Completed!</p>
            {% else %}
                <p class="border-bottom text-danger">Incompleted!</p>
            {% endif %}
        </div>
        {% endfor %}
{% endblock %}

final_project/clock/templates/clock/task_update.html
{% extends 'clock/base.html' %}

{% block body %}
    <h1 class="border-bottom font-italic pb-2">Update Task</h1>
    <div class="text-center m-3 p-2">
        <form method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
    </div>
{% endblock %}